---
name : learning
on :
    push :
        branches :
            - main
jobs :
    exercise1 :
        runs-on : ubuntu-latest
        steps : 
            - name : learning
              run : echo "hello how are you"